name: 'scp_eploy'
description: 'Deploy code to a remote server using SCP'
inputs:
  host:
    description: 'The IP or domain-name of your server'
    required: true
  user:
    description: 'The username to connect with'
    required: true
  port:
    description: 'Port to use with your connection'
    default: '22'
  private_key:
    description: 'Your private key as string'
    required: true
  source_folder:
    description: 'Directory to upload'
    required: true
  destination_folder:
    description: 'Directory to upload files into'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
