name: "scp deployment"
description: "Deploy files to remote server over SSH"
inputs:

  host:
    description: "The IP or domain-name of your server"
    required: true
  user: 
    description: "The username to connect with"
    required: true
  port: 
    description: "Port to use with your connection"
    required: false
    default: 22
  private_key:
    description: "Your private key as string"
    required: true
    default: ""

  working_directory:
    description: ""
    required: true
  source_folder:
    description: "Directory to upload"
    required: true
  destination_folder:
    description: "Directory to upload files into"
    required: false
    default: "."
  versioning:
    description: "publish new deploys in folders with a build number representing it's version. (newer versions get higher build number)"
    required: false
    default: false
  public_directory:
    description: "Public folder accessable from webclient"
    required: false
    default: "Current"
  versions_directory:
    description: "Name of folder to keep different versions"
    required: false
    default: "Versions"

runs:
  using: 'node16'
  main: "dist/index.js"